{{- if .Values.nodeAgent.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "hcs.fullname" . }}-node-agent
  labels:
    {{- include "hcs.nodeAgent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "hcs.fullname" . }}-node-agent
subjects:
  - kind: ServiceAccount
    name: {{ include "hcs.nodeAgent.serviceAccountName" . }}
    namespace: {{ include "hcs.namespace" . }}
{{- end }}
