{{- if and .Values.nodeAgent.enabled .Values.nodeAgent.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hcs.nodeAgent.serviceAccountName" . }}
  namespace: {{ include "hcs.namespace" . }}
  labels:
    {{- include "hcs.nodeAgent.labels" . | nindent 4 }}
  {{- with .Values.nodeAgent.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
