{{- if .Values.scheduler.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "hcs.fullname" . }}-scheduler
  labels:
    {{- include "hcs.scheduler.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "hcs.fullname" . }}-scheduler
subjects:
  - kind: ServiceAccount
    name: {{ include "hcs.scheduler.serviceAccountName" . }}
    namespace: {{ include "hcs.namespace" . }}
{{- end }}
