{{- if and .Values.scheduler.enabled .Values.scheduler.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hcs.scheduler.serviceAccountName" . }}
  namespace: {{ include "hcs.namespace" . }}
  labels:
    {{- include "hcs.scheduler.labels" . | nindent 4 }}
  {{- with .Values.scheduler.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
