{{- if and .Values.webhook.enabled .Values.webhook.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "hcs.fullname" . }}-selfsigned-issuer
  namespace: {{ include "hcs.namespace" . }}
  labels:
    {{- include "hcs.webhook.labels" . | nindent 4 }}
spec:
  selfSigned: {}
{{- end }}
