{{- if .Values.webhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "hcs.fullname" . }}-webhook
  labels:
    {{- include "hcs.webhook.labels" . | nindent 4 }}
  {{- if .Values.webhook.certManager.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: {{ include "hcs.namespace" . }}/{{ include "hcs.webhook.certificateName" . }}
  {{- end }}
webhooks:
  - name: pod-injector.hcs.hetero.zrs.io
    admissionReviewVersions:
      - v1
    clientConfig:
      {{- if not .Values.webhook.certManager.enabled }}
      {{- if .Values.webhook.tls.caBundle }}
      caBundle: {{ .Values.webhook.tls.caBundle | b64enc }}
      {{- end }}
      {{- end }}
      service:
        name: {{ include "hcs.webhook.serviceName" . }}
        namespace: {{ include "hcs.namespace" . }}
        path: /mutate/pods
        port: 443
    failurePolicy: {{ .Values.webhook.failurePolicy }}
    matchPolicy: Equivalent
    namespaceSelector:
      matchExpressions:
        - key: hcs.hetero.zrs.io/enabled
          operator: NotIn
          values:
            - "false"
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
            - kube-public
            - kube-node-lease
            {{- if ne (include "hcs.namespace" .) "default" }}
            - {{ include "hcs.namespace" . }}
            {{- end }}
    objectSelector:
      matchExpressions:
        - key: hcs.hetero.zrs.io/skip-injection
          operator: NotIn
          values:
            - "true"
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
        scope: Namespaced
    sideEffects: None
    timeoutSeconds: 10
{{- end }}
