{{- if and .Values.webhook.enabled .Values.webhook.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hcs.webhook.serviceAccountName" . }}
  namespace: {{ include "hcs.namespace" . }}
  labels:
    {{- include "hcs.webhook.labels" . | nindent 4 }}
  {{- with .Values.webhook.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
